name: deploy

on:
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        description: ログレベル
        default: warning

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
